[general]
font-sans = "Noto Sans"
font-mono = "Noto Sans Mono"

[bar]
scale = 0.800000011920929
inset-edge = 0.6700000166893005
inset-ends = 24.0
border-location = "left"
border-width = 2
rounding = "sm"
button-variant = "basic"
button-bg-opacity = 0
button-label-size = 1.0499999523162842
button-label-weight = "bold"
button-label-padding = 0.8500000238418579

[[bar.layout]]
monitor = "*"
show = true
left = [
    { name = "LEFT", modules = [
    "dashboard",
    "hyprland-workspaces",
] },
    "cava",
]
center = [
    "separator",
    { name = "INFO", modules = [
    "notifications",
    "clock",
] },
]

[[bar.layout.right]]
name = "SYSTRAY"
modules = ["systray"]

[[bar.layout.right]]
name = "RIGHT"
modules = [
    "network",
    "bluetooth",
    "microphone",
    "volume",
    "brightness",
    "idle-inhibit",
    "battery",
]

[[bar.layout.right]]
name = "POWER"
modules = ["power"]

[styling.palette]
bg = "#11111b"
surface = "#181825"
elevated = "#1e1e2e"
fg = "#cdd6f4"
fg-muted = "#bac2de"
primary = "#b4befe"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
blue = "#74c7ec"

[modules.battery]
icon-color = "accent"
label-color = "accent"

[modules.bluetooth]
icon-color = "accent"
label-show = false
label-max-length = 24
right-click = "blueman-manager"

[modules.brightness]
icon-color = "accent"
label-color = "accent"
right-click = "pkill hyprsunset || hyprsunset -t 5000"
scroll-up = "brightnessctl set 5%+"
scroll-down = "brightnessctl set 5%-"

[modules.cava]
bars = 28
direction = "mirror"
button-bg-color = "transparent"
left-click = "dropdown:media"

[modules.clock]
format = "%A %d %B / %I:%M %p"
icon-show = false

[modules.dashboard]
icon-color = "accent"
left-click = 'hyprctl dispatch "hl.plugin.hymission.toggle"'
dropdown-lock-command = "hyprlock"

[modules.hyprland-workspaces]
min-workspace-count = 10
monitor-specific = false
show-special = false
workspace-padding = 0.699999988079071

[modules.idle-inhibit]
startup-duration = 0
icon-color = "accent"
label-show = false

[modules.microphone]
icon-color = "accent"
label-show = false
right-click = "wayle audio input-mute"
middle-click = ""

[modules.network]
label-show = false
label-max-length = 24

[modules.notifications]
icon-color = "accent"
label-show = false
popup-position = "top-center"

[modules.power]
icon-color = "accent"
left-click = "wlogout -b 5 -T 350 -B 350"

[modules.volume]
icon-color = "accent"
label-color = "accent"
right-click = "wayle audio output-mute"
middle-click = ""
scroll-up = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ --limit 1"
scroll-down = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"

[modules.weather]
location = "Ameca"

[osd]
monitor = "HDMI-A-1"

[wallpaper]
engine-enabled = false
