font_family Noto Sans Mono
font_size 11

cursor #ffffff
cursor_shape underline
cursor_blink_interval 0.250
cursor_stop_blinking_after 0
shell_integration no-cursor

foreground #a9b1d6
background #181825

# Black
color0 #32344a
color8 #444b6a

# Red
color1 #f7768e
color9 #ff7a93

# Green
color2  #9ece6a
color10 #b9f27c

# Yellow
color3  #e0af68
color11 #ff9e64

# Blue
color4  #7aa2f7
color12 #7da6ff

# Magenta
color5  #ad8ee6
color13 #bb9af7

# Cyan
color6  #449dab
color14 #0db9d7

# White
color7  #787c99
color15 #acb0d0
