# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita iniciar múltiples instancias de hyprlock
    before_sleep_cmd = loginctl lock-session    # (Opcional) Bloquea si alguna vez suspendes manualmente
    after_sleep_cmd = hyprctl dispatch dpms on  # Asegura que la pantalla encienda al despertar
}

# Alerta y reducción de brillo tras 90 segundos de inactividad
listener {
    timeout = 90
    on-timeout = notify-send "Hypridle" "La pantalla se bloqueará en 30 segundos !!" -t 10000 & brightnessctl -s set 37%
    on-resume = brightnessctl -r
}

# Bloqueo de pantalla tras 120 segundos de inactividad
listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

