# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita iniciar múltiples instancias de hyprlock
    before_sleep_cmd = loginctl lock-session    # (Opcional) Bloquea si alguna vez suspendes manualmente
    after_sleep_cmd = hyprctl dispatch dpms on  # Asegura que la pantalla encienda al despertar
}

# Alerta y reducción de brillo a los 4 minutos (240 segundos)
listener {
    timeout = 240
    on-timeout = notify-send "Hypridle" "La pantalla se bloqueará en 1 minuto" -t 10000 & brightnessctl -s set 25%-
    on-resume = brightnessctl -r
}

# Bloqueo de pantalla a los 5 minutos (300 segundos)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

