# ~/.config/hypr/hyprlock.conf

background {
    path = screenshot
    blur_passes = 3 
    blur_size = 6    
}

label {
    text = $TIME12
    color = rgba(192, 202, 245, 1.0)
    font_size = 67
    font_family = JetBrains Mono Nerd Font Bold
    position = 0, 150
    halign = center
    valign = center
}

input-field {
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.40
    dots_center = true

    outer_color = rgb(26, 27, 37)     # Tokyo Night Black
    inner_color = rgb(36, 40, 59)     
    font_color = rgb(192, 202, 245)   
    fade_on_empty = false
    
    placeholder_text = <i>. . .</i>
    hide_input = false

    check_color = rgb(122, 162, 247)
    fail_color = rgb(247, 118, 142)
    fail_text = <i>. . .</i>
    fail_transition = 0
    
    position = 0, -20
    halign = center
    valign = center
}
