# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid creating multiple instances.
    before_sleep_cmd = loginctl lock-session    # lock screen (hyprlock) on suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # Ensures the screen turns on when waking up
}

# Notification + set brightness to 37% | after 90 seconds of inactivity
listener {
    timeout = 90
    on-timeout = notify-send "Hypridle" "La pantalla se bloqueará en 30 segundos !!" -t 10000 & brightnessctl -s set 37%
    on-resume = brightnessctl -r
}

# Screen lock (hyprlock) | after 2 minutes of inactivit
listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

