[general]
font-sans = "Noto Sans"
font-mono = "Noto Sans Mono"

[bar]
scale = 0.800000011920929
inset-edge = 0.4000000059604645
inset-ends = 0.800000011920929
bg = "bg-base"
background-opacity = 90
rounding = "sm"
button-variant = "basic"
button-bg-opacity = 0
button-label-size = 1.0499999523162842
button-label-weight = "bold"

[[bar.layout]]
monitor = "*"
show = true
left = [
    { name = "POWER", modules = [
    "separator",
    "power",
    "separator",
] },
    { name = "INFO", modules = [
    "separator",
    "notifications",
    "clock",
    "separator",
] },
    "cava",
    { name = "WORK", modules = [
    "separator",
    "hyprland-workspaces",
    "separator",
] },
]
center = []

[[bar.layout.right]]
name = "SYSTRY"
modules = [
    "separator",
    "systray",
    "separator",
]

[[bar.layout.right]]
name = "WB"
modules = [
    "separator",
    "network",
    "bluetooth",
    "separator",
]

[[bar.layout.right]]
name = "I/O"
modules = [
    "separator",
    "microphone",
    "volume",
    "brightness",
    "battery",
    "separator",
]

[[bar.layout.right]]
name = "D3H"
modules = [
    "separator",
    "dashboard",
    "separator",
]

[styling.palette]
bg = "#11111b"
surface = "#181825"
elevated = "#1e1e2e"
fg = "#cdd6f4"
fg-muted = "#bac2de"
primary = "#a9b1d6"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
blue = "#74c7ec"

[modules.battery]
icon-color = "accent"
label-color = "accent"

[modules.bluetooth]
icon-color = "accent"
label-color = "accent"
label-max-length = 24

[modules.brightness]
icon-color = "accent"
label-color = "accent"
right-click = "pkill hyprsunset || hyprsunset -t 5000"
scroll-up = "brightnessctl set 5%+"
scroll-down = "brightnessctl set 5%-"

[modules.cava]
bars = 62
direction = "mirror"
button-bg-color = "transparent"
left-click = "dropdown:media"

[modules.clock]
format = "%A %d %B / %I:%M %p"
icon-show = false

[modules.dashboard]
icon-color = "accent"
dropdown-lock-command = "hyprlock"

[modules.hyprland-workspaces]
min-workspace-count = 10
monitor-specific = false
show-special = false
app-icons-show = true

[modules.microphone]
icon-color = "accent"
label-show = false
right-click = "wayle audio input-mute"
middle-click = ""

[modules.network]
icon-color = "accent"
label-max-length = 24

[modules.notifications]
icon-color = "accent"
label-show = false
label-color = "accent"
popup-position = "top-left"
popup-margin-x = 3.0
popup-margin-y = 3.0

[modules.power]
icon-color = "accent"
left-click = "wlogout --buttons-per-row 5"

[modules.volume]
icon-color = "accent"
label-color = "accent"
right-click = "wayle audio output-mute"
middle-click = ""
scroll-up = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ --limit 1"
scroll-down = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"

[modules.weather]
location = "Ameca"

[wallpaper]
engine-enabled = false
